name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  issue_title:  # id of input
    description: 'Title to slugify'
    required: true
    default: 'Example Title'
  cloudflare_account_id:  # id of input
    description: 'Cloudflare Account'
    required: true
    default: '123'
  cloudflare_namespace_id:  # id of input
    description: 'Namespace'
    required: true
    default: '456'
  cloudflare_token:  # id of input
    description: 'API Key for Cloudflare'
    required: true
    default: '789'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  slug: # id of output
    description: 'title turned slug'
  issue_id: # id of output
    description: 'issue id'
runs:
  using: 'node16'
  main: 'index.js'
