name: "Slugify Issue"
description: "Create slug from title of Github Issue. Trigger on Issue Update."
inputs:
  namespace_identifier: # id of input
    description: "Cloudflare Namespace Identifier"
    required: true
    default: "456"
outputs:
  slug: # id of output
    description: "Title of Issue turned slug"
  issue_number: # id of output
    description: "Issue number"
runs:
  using: "node16"
  main: "index.js"
